export const USERS = {
    LOAD_LIST_REQUEST: "USERS_LOAD_LIST_REQUEST",
    LOAD_LIST_SUCCESS: "USERS_LOAD_LIST_SUCCESS",
    LOAD_LIST_FAILURE: "USERS_LOAD_LIST_FAILURE",

    LOAD_REQUEST: "USERS_LOAD_REQUEST",
    LOAD_SUCCESS: "USERS_LOAD_SUCCESS",
    LOAD_FAILURE: "USERS_LOAD_FAILURE",

    CREATE_SUCCESS: "USERS_CREATE_SUCCESS",

    PUT_REQUEST: "USERS_PUT_REQUEST",
    PUT_SUCCESS: "USERS_PUT_SUCCESS",
    PUT_FAILURE: "USERS_PUT_FAILURE",
};